更新挑战系统，允许少量相似字符
zly2006/yet-another-qq-bot pull request #11
Opened 2023-05-07 03:05 UTC by Normal-pcer

当玩家回答出现1个相似字符时：
- 玩家会获得1~8个金币（上下限均比正常情况少两个）
- 玩家不会获得连续答对的额外奖励
- 若该玩家下次完全答对，仍会记为连续答对 相似字符包括["Cc", "Ff", "Il1", "Kk", "Mm", "Oo0", "Pp", "Ss", "Uu", "Vv", "Ww", "Xx", "Zz"]

在挑战系统中，有时会分不清部分大小写字母或其它相似字符，这是一种解决方案——答案出现少量相似字符仍然给予少量奖励。

2023-05-09 14:47 UTC, zly2006 requested changes

2023-05-09 14:47 UTC, zly2006 commented on src/main/kotlin/Challenge.kt
> +                for (i in 0 until message.content.length) {
请处理可能的越界

2023-05-09 14:47 UTC, zly2006 commented on src/main/kotlin/Challenge.kt
> +                    "Cc", "Ff", "Il1", "Kk",
Ff、Kk、Mm是不必要的

2023-05-09 14:53 UTC, Normal-pcer commented on src/main/kotlin/Challenge.kt
> +                    "Cc", "Ff", "Il1", "Kk",
我认为Kk有必要

2023-05-09 14:55 UTC, zly2006 commented on src/main/kotlin/Challenge.kt
> +                    "Cc", "Ff", "Il1", "Kk",
形状差异很大，应予移除

2023-05-10 06:20 UTC, zly2006 commented
判断一下防越界

2023-05-11 06:25 UTC, Normal-pcer commented
若您说的越界是指这句
```kotlin
val userInput = message.content[i]
val answer = lastKey.toString()[i]```
则不可能越界，因为前文已经保证了userInput和answer长度一样且answer不为null

2023-05-11 06:38 UTC, zly2006 commented
> 若您说的越界是指这句
> 
> ```kotlin
> val userInput = message.content[i]
> val answer = lastKey.toString()[i]
> ```
> 
> 则不可能越界，因为前文已经保证了userInput和answer长度一样且answer不为null

我的问题

2023-05-11 06:39 UTC, zly2006 approved these changes

2023-05-11 06:41 UTC, merged